config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :genres, only: [:index, :show, :new, :create, :edit, :update]
  resources :directors, only: [:index, :show, :new, :create, :edit, :update]
  resources :movies, only: [:index, :show, :new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/director.rb
class Director < ApplicationRecord
  belongs_to :genre
  has_many :movies
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :directors
  has_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :genre
  belongs_to :director
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  def index
    @directors = Director.all
  end

  def show
    @director = Director.find(params[:id])
  end

  def new
    @director =  Director.new
  end

  def create
    @director = Director.new(params.require(:director).permit(:name, :nationality, :birth_date, :genre_id))
    if @director.save
      return redirect_to director_path(@director.id)
    end

    render :new
  end

  def edit
    @director = Director.find(params[:id])
  end

  def update
    @director = Director.find(params[:id])

    if @director.update( params.require(:director).permit(:name,:nationality, :birth_date, :genre_id))
      return redirect_to director_path(@director.id)
    end

    render :edit
  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

  def index
    @genres = Genre.all
  end

  def show
    @genre = Genre.find(params[:id])
  end

  def new
    @genre =  Genre.new
  end

  def create
    @genre =  Genre.new(params.require(:genre).permit(:genre_name))
    if @genre.save
      return redirect_to genre_path(@genre.id)
    end

    render :new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    
    if @genre.update(params.require(:genre).permit(:genre_name))
      return redirect_to genre_path(@genre.id)
    end

    render :edit

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index 
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new 
    @movie = Movie.new
  end

  def create 
    @movie = Movie.create(params.require(:movie).permit(:title, :release_year, :synopsis, :country_of_origin, :duration, :director_id, :genre_id))

    if @movie.save
      return redirect_to movie_path(@movie.id)
    end

    render :new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    
    if Movie.update(params.require(:movie).permit(:title, :release_year, :synopsis, :country_of_origin, :duration, :director_id, :genre_id))
      return redirect_to movie_path(@movie.id)
    end
    render :edit
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/directors/_form.html.erb
<%= form_with model: director do |f|%>

  <%= f.label 'Nome' %>
  <%= f.text_field :name %>

  <%= f.label 'Nacionalidade' %>
  <%= f.text_field :nationality %>

  <%= f.label 'Data de nascimento' %>
  <%= f.date_field :birth_date %>
  
  <%= f.label 'Genero favoritos' %>
  <%= f.collection_select :genre_id, Genre.all, :id, :genre_name %>


  <%= f.submit 'Salvar' %>

<%end%>

app/views/directors/edit.html.erb
<h1> Edite o director :</h1>

<%= render partial: 'form', locals: {director: @director} %>

app/views/directors/index.html.erb
<h1>Diretores : </h1>

<% @directors.each do |director| %>

  <%= link_to director.name, director %>
  <br>

<% end %>
    

app/views/directors/new.html.erb
<h1> Cadastre um novo director :</h1>

<%= render partial: 'form', locals: {director: @director} %>

app/views/directors/show.html.erb
<br>
<h1>Informações sobre o diretor: <%=@director.name%> </h1>

<%= link_to 'Editar', edit_director_path %>

<dl>
    <dt>
      <strong> Nome:</strong> <%= @director.name %>
    </dt>

    <dt>
      <strong> Nacionalidade:</strong> <%= @director.nationality %>
    </dt>

    <dt>
      <strong> Data de nascimento:</strong> <%= @director.birth_date %>
    </dt>

    <dt>
      <strong> Genero Favorito:</strong> <%= @director.genre.genre_name %>
    </dt>

</dl>w

app/views/genres/_form.html.erb
<%= form_with model: genre do |f|%>
  <%= f.label 'Nome do genero' %>
  <%= f.text_field :genre_name %>
  <%= f.submit 'Salvar' %>

<%end%>

app/views/genres/edit.html.erb
<h1> Edite um novo genero :</h1>

<%= render partial: 'form', locals: {genre: @genre} %>

app/views/genres/index.html.erb
<h1>Generos : </h1>

<% @genres.each do |genre| %>

  <%= link_to genre.genre_name, genre %>
  <br>

<% end %>
    

app/views/genres/new.html.erb
<h1> Cadastre um novo genero :</h1>

<%= render partial: 'form', locals: {genre: @genre} %>

app/views/genres/show.html.erb
<br>

<%= @genre.genre_name %> 
<br>
<%= link_to 'Editar', edit_genre_path %>

app/views/home/index.html.erb
<ul>
  <li>
    <%= link_to 'Todos os generos', genres_path%>
  </li>

  <li>
  <%= link_to 'Cadastrar novo genero', new_genre_path %>
  </li>

  <li>
    <%= link_to 'Todos os Diretores', directors_path%>
  </li>

  <li>
  <%= link_to 'Cadastrar novo Diretor', new_director_path %>
  </li>


  <li>
    <%= link_to 'Todos os Filmes', movies_path%>
  </li>

  <li>
  <%= link_to 'Cadastrar novo Filme', new_movie_path %>
  </li>
  

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Catalogo de Filmes </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav>
      <ul>
        <li>
          <%= link_to 'Home', root_path%>
        </li>
      </ul>
    </nav>  

    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with model: movie do |f|%>

  <%= f.label 'Titulo' %>
  <%= f.text_field :title %>

  <%= f.label 'Ano de lançamento' %>
  <%= f.number_field :release_year %>

  <%= f.label 'Sinopse' %>
  <%= f.text_area :synopsis %>

  <%= f.label 'Pais de Origem' %>
  <%= f.text_field :country_of_origin %>

  <%= f.label 'Duração(minutos) ' %>
  <%= f.number_field :duration %>

  <%= f.label 'Diretor do filme' %>
  <%= f.collection_select :director_id, Director.all, :id, :name %>
  
  <%= f.label 'Genero do filme' %>
  <%= f.collection_select :genre_id, Genre.all, :id, :genre_name %>

  <%= f.submit 'Salvar' %>

<%end%>

app/views/movies/edit.html.erb
<h1> Edite o Filme :</h1>

<%= render partial: 'form', locals: {movie: @movie} %>

app/views/movies/index.html.erb
<h1>Filmes: </h1>

<% @movies.each do |movie|%>
  
  <%= link_to movie.title, movie %>

<%end%>

app/views/movies/new.html.erb
<h1> Cadastre um novo Filme :</h1>

<%= render partial: 'form', locals: {movie: @movie} %>

app/views/movies/show.html.erb
<br>
<h1>Informações sobre o filme: <%=@movie.title%> </h1>

<%= link_to 'Editar', edit_movie_path %>

<dl>
    <dt>
      <strong> Titulo:</strong> <%= @movie.title %>
    </dt>

    <dt>
      <strong> Ano de lançamento:</strong> <%= @movie.release_year %>
    </dt>

    <dt>
      <strong> Sinopse:</strong> <%= @movie.synopsis %>
    </dt>

    <dt>
      <strong> Pais de origem:</strong> <%= @movie.country_of_origin %>
    </dt>

    <dt>
      <strong> Duração:</strong> <%= @movie.duration %> minutos
    </dt>

    <dt>
      <strong> Diretor:</strong> <%= @movie.director.name %> 
    </dt>

    <dt>
      <strong> Genero:</strong> <%= @movie.genre.genre_name %>
    </dt>


</dl>